# Configure OIDC
quarkus.oidc.auth-server-url=${KEYCLOAK_URL}
quarkus.oidc.client-id=${KEYCLOAK_CLIENT_ID}
quarkus.oidc.credentials.secret=${KEYCLOAK_CLIENT_SECRET}

# Configure OIDC Client
quarkus.oidc-client.auth-server-url=${quarkus.oidc.auth-server-url}
quarkus.oidc-client.client-id=${quarkus.oidc.client-id}
quarkus.oidc-client.credentials.secret=${quarkus.oidc.credentials.secret}
quarkus.oidc-client.grant.type=exchange
quarkus.oidc-client.grant-options.exchange.requested_issuer=google
quarkus.oidc-token-propagation-reactive.exchange-token=true

# Configure Rest Clients
com.viniciuscastro.slides.clients.GoogleSlidesClient/mp-rest/url=https://slides.googleapis.com/v1/presentations
com.viniciuscastro.slides.clients.GoogleDriveClient/mp-rest/url=https://www.googleapis.com/drive/v3/files

# Configure Logs
quarkus.rest-client.logging.scope=request-response
quarkus.rest-client.logging.body-limit=1024
quarkus.log.category."org.jboss.resteasy.reactive.client.logging".level=DEBUG
quarkus.log.level=ALL
